# Generated by Django 4.1.13 on 2023-11-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0002_crawledpage_availability_crawledpage_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawledpage',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='crawledpage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='crawledpage',
            name='price',
        ),
        migrations.AlterField(
            model_name='crawledpage',
            name='title',
            field=models.CharField(max_length=400),
        ),
    ]
